<a href="https://colab.research.google.com/github/swampxx/ML-algorithms-on-ids-datasets/blob/master/IDS_2018_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import numpy as np

from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDClassifier
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import (precision_score, recall_score, f1_score, accuracy_score, mean_squared_error, mean_absolute_error)
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error, roc_curve, classification_report,auc)


In [3]:
!ls drive/My\ Drive/security_term_project/

66398.pdf			      test_y_processed_fi.txt
ids_2018_thursday.csv		      test_y_processed_kbest.txt
ids2018-thursday_final_df_labels.txt  train_x_processed_fi.txt
ids2018-thursday_final_df.txt	      train_x_processed_kbest.txt
test_x_processed_fi.txt		      train_y_processed_fi.txt
test_x_processed_kbest.txt	      train_y_processed_kbest.txt


In [4]:
path = "drive/My Drive/security_term_project/"

In [5]:
data = np.loadtxt(path+"ids2018-thursday_final_df.txt")
labels = np.loadtxt(path+"ids2018-thursday_final_df_labels.txt")

In [6]:
trainX, testX, trainY, testY = train_test_split(data, labels, test_size=0.2, random_state=42)

In [7]:
trainX.shape, trainY.shape, testX.shape, testY.shape

((832438, 55), (832438,), (208110, 55), (208110,))

## Logistic Regression

In [28]:
model = LogisticRegression(max_iter=10000)
model.fit(trainX, trainY)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [30]:
# make predictions
predicted = model.predict(testX)


In [31]:
accuracy_score(testY, predicted)

0.9735908894334727

In [32]:
precision_score(testY, predicted)

0.9114192495921697

In [37]:
recall_score(testY, predicted)

0.5300759013282732

In [41]:
print(classification_report(testY, predicted))
print(confusion_matrix(testY, predicted))

              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99    197570
         1.0       0.91      0.53      0.67     10540

    accuracy                           0.97    208110
   macro avg       0.94      0.76      0.83    208110
weighted avg       0.97      0.97      0.97    208110

[[197027    543]
 [  4953   5587]]


## Random Forest

GridSearchCV is used for model selection, since it takes too much time
it is executed on another machine. 

```
pipeline = make_pipeline(RandomForestClassifier())

#Add a dict of estimator and estimator related parameters in this list

hyperparameters = {
                'randomforestclassifier__n_estimators': [25,50,75,100],
                'randomforestclassifier__max_features' : [None, "log2", "auto"]
                }
               
clf = GridSearchCV(pipeline, hyperparameters, cv=5,verbose=1,n_jobs=-1)
clf.fit(_traindata, _trainlabel)
```
RESULTS: n_estimator: 100 , max_feature: 'log2'



In [33]:
rf = RandomForestClassifier(n_estimators=100, max_features="log2")

rf.fit(trainX, trainY)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='log2',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [34]:
rf_predicted = rf.predict(testX)

accuracy_score(testY, rf_predicted)

0.999985584546634

In [35]:
precision_score(testY, rf_predicted)

0.9999051143372236

In [36]:
recall_score(testY, rf_predicted)

0.9998102466793168

In [40]:
print(classification_report(testY, rf_predicted))
print(confusion_matrix(testY, rf_predicted))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    197570
         1.0       1.00      1.00      1.00     10540

    accuracy                           1.00    208110
   macro avg       1.00      1.00      1.00    208110
weighted avg       1.00      1.00      1.00    208110

[[197569      1]
 [     2  10538]]


## Naive Bayes



In [42]:
nb = GaussianNB()

nb.fit(trainX, trainY)

GaussianNB(priors=None, var_smoothing=1e-09)

In [43]:
nb_predicted = nb.predict(testX)

In [44]:
print(classification_report(testY, nb_predicted))
print(confusion_matrix(testY, nb_predicted))

              precision    recall  f1-score   support

         0.0       0.96      0.89      0.92    197570
         1.0       0.14      0.33      0.19     10540

    accuracy                           0.86    208110
   macro avg       0.55      0.61      0.56    208110
weighted avg       0.92      0.86      0.89    208110

[[176039  21531]
 [  7094   3446]]


## K Nearest Neighbor


In [45]:
knn = KNeighborsClassifier()

knn.fit(trainX, trainY)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [46]:
knn_predicted = knn.predict(testX)

In [47]:
print(classification_report(testY, knn_predicted))
print(confusion_matrix(testY, knn_predicted))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    197570
         1.0       0.99      0.99      0.99     10540

    accuracy                           1.00    208110
   macro avg       0.99      1.00      0.99    208110
weighted avg       1.00      1.00      1.00    208110

[[197415    155]
 [    54  10486]]


## Decision Tree Classifier

In [54]:
dt = DecisionTreeClassifier()

dt.fit(trainX, trainY)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [55]:
dt_predicted = dt.predict(testX)

In [56]:
print(classification_report(testY, dt_predicted))
print(confusion_matrix(testY, dt_predicted))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    197570
         1.0       1.00      1.00      1.00     10540

    accuracy                           1.00    208110
   macro avg       1.00      1.00      1.00    208110
weighted avg       1.00      1.00      1.00    208110

[[197569      1]
 [     1  10539]]


## AdaBoost

In [63]:
ada = AdaBoostClassifier()

ada.fit(trainX, trainY)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

In [64]:
ada_predicted = ada.predict(testX)

In [65]:
print(classification_report(testY, ada_predicted))
print(confusion_matrix(testY, ada_predicted))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    197570
         1.0       1.00      1.00      1.00     10540

    accuracy                           1.00    208110
   macro avg       1.00      1.00      1.00    208110
weighted avg       1.00      1.00      1.00    208110

[[197569      1]
 [     0  10540]]


## Multi Layer Perceptrons

In [71]:
mlp = MLPClassifier(random_state=16, max_iter=300)

mlp.fit(trainX, trainY)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=300,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=16, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [73]:
mlp_predicted = mlp.predict(testX)

In [74]:
print(classification_report(testY, mlp_predicted))
print(confusion_matrix(testY, mlp_predicted))

              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97    197570
         1.0       1.00      0.00      0.01     10540

    accuracy                           0.95    208110
   macro avg       0.97      0.50      0.49    208110
weighted avg       0.95      0.95      0.93    208110

[[197570      0]
 [ 10490     50]]


## Quadratic Discriminant Analysis

In [8]:
qda = QuadraticDiscriminantAnalysis()

qda.fit(trainX, trainY)

/usr/local/lib/python3.6/dist-packages/sklearn/discriminant_analysis.py:691: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)

In [9]:
qda_predicted = qda.predict(testX)

In [10]:
print(classification_report(testY, qda_predicted))
print(confusion_matrix(testY, qda_predicted))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    197570
         1.0       1.00      0.99      1.00     10540

    accuracy                           1.00    208110
   macro avg       1.00      1.00      1.00    208110
weighted avg       1.00      1.00      1.00    208110

[[197569      1]
 [    59  10481]]


## SVM

In [ ]:
svc = SVC()

svc.fit(trainX, trainY)

In [ ]:
svc_predicted = svc.predict(testX)

In [ ]:
print(classification_report(testY, svc_predicted))
print(confusion_matrix(testY, svc_predicted))